<?php

namespace Database\Seeders;

use App\Models\Account;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class AccountsSeeder extends Seeder
{
    public function run(): void
    {
        $roots = [
            [
                "id"=> 1,
                "name" => "الأصول",
                "code" => "1",
                "parent_id" => null,
                "type_id" => 1,
                "level" => 1,
                "is_active" => 1,
            ],
            [
                "id" => 2,
                "name" => "الخصوم",
                "code" => "2",
                "parent_id" => null,
                "type_id" => 2,
                "level" => 1,
                "is_active" => 1,
            ],
            [
                "id" => 3,
                "name" => "المصاريف",
                "code" => "3",
                "parent_id" => null,
                "type_id" => 3,
                "level" => 1,
                "is_active" => 1,
            ],
            [
                "id" => 4,
                "name" => "الإيرادات",
                "code" => "4",
                "parent_id" => null,
                "type_id" => 4,
                "level" => 1,
                "is_active" => 1,
            ],
            [
                "id" => 5,
                "name" => "اصول متداولة",
                "code" => "101",
                "parent_id" => 1,
                "type_id" => 1,
                "level" => 2,
                "is_active" => 1,
            ],
            [
                "id" => 6,
                "name" => "اصول ثابتة",
                "code" => "102",
                "parent_id" => 1,
                "type_id" => 1,
                "level" => 2,
                "is_active" => 1,
            ],
            [
                "id" => 7,
                "name" => "ارصدة مدينة اخرى",
                "code" => "103",
                "parent_id" => 1,
                "type_id" => 1,
                "level" => 2,
                "is_active" => 1,
            ],
            [
                "id" => 8,
                "name" => "خصوم قصيرة الأجل",
                "code" => "201",
                "parent_id" => 2,
                "type_id" => 2,
                "level" => 2,
                "is_active" => 1,
            ],
            [
                "id" => 9,
                "name" => "خصوم طويلة الأجل",
                "code" => "202",
                "parent_id" => 2,
                "type_id" => 2,
                "level" => 2,
                "is_active" => 1,
            ],
            [
                "id" => 10,
                "name" => "أرصدة دائنة اخرى",
                "code" => "203",
                "parent_id" => 2,
                "type_id" => 2,
                "level" => 2,
                "is_active" => 1,
            ],
            [
                "id" => 11,
                "name" => "حقوق الملكية",
                "code" => "204",
                "parent_id" => 2,
                "type_id" => 2,
                "level" => 2,
                "is_active" => 1,
            ],
            [
                "id" => 12,
                "name" => "المصروفات",
                "code" => "301",
                "parent_id" => 3,
                "type_id" => 3,
                "level" => 2,
                "is_active" => 1,
            ],
            [
                "id" => 13,
                "name" => "المصروفات",
                "code" => "30101",
                "parent_id" => 12,
                "type_id" => 3,
                "level" => 3,
                "is_active" => 1,
            ],
            [
                "id" => 14,
                "name" => "مصاريف التشغيل",
                "code" => "3010101",
                "parent_id" => 13,
                "type_id" => 3,
                "level" => 4,
                "is_active" => 1,
            ],
            [
                "id" => 15,
                "name" => "المصاريف العمومية",
                "code" => "3010102",
                "parent_id" => 13,
                "type_id" => 3,
                "level" => 4,
                "is_active" => 1,
            ],
            [
                "id" => 16,
                "name" => "رواتب واجور",
                "code" => "30101010001",
                "parent_id" => 14,
                "type_id" => 3,
                "level" => 5,
                "is_active" => 1,
            ],
            [
                "id" => 17,
                "name" => "رواتب و اجور",
                "code" => "30101020001",
                "parent_id" => 15,
                "type_id" => 3,
                "level" => 5,
                "is_active" => 1,
            ],
            [
                "id" => 22,
                "name" => "النقدية والبنوك",
                "code" => "10101",
                "parent_id" => 5,
                "type_id" => 1,
                "level" => 3,
                "is_active" => 1,
            ],
            [
                "id" => 23,
                "name" => "النقدية",
                "code" => "1010101",
                "parent_id" => 22,
                "type_id" => 1,
                "level" => 4,
                "is_active" => 1,
            ],
            [
                "id" => 24,
                "name" => "البنوك",
                "code" => "1010102",
                "parent_id" => 22,
                "type_id" => 1,
                "level" => 4,
                "is_active" => 1,
            ],
            [
                "id" => 25,
                "name" => "صندوق الساحة",
                "code" => "10101010001",
                "parent_id" => 23,
                "type_id" => 1,
                "level" => 5,
                "is_active" => 1,
            ],
            [
                "id" => 26,
                "name" => "البنك الاهلي",
                "code" => "10101020001",
                "parent_id" => 24,
                "type_id" => 1,
                "level" => 5,
                "is_active" => 1,
            ],
            [
                "id" => 27,
                "name" => "العملاء",
                "code" => "10102",
                "parent_id" => 5,
                "type_id" => 1,
                "level" => 3,
                "is_active" => 1,
            ],
            [
                "id" => 28,
                "name" => "المخزون",
                "code" => "10103",
                "parent_id" => 5,
                "type_id" => 1,
                "level" => 3,
                "is_active" => 1,
            ],
            [
                "id" => 30,
                "name" => "عملاء التشغيل",
                "code" => "1010201",
                "parent_id" => 27,
                "type_id" => 1,
                "level" => 4,
                "is_active" => 1,
            ],
            [
                "id" => 39,
                "name" => "مخزون قطع غيار",
                "code" => "1010301",
                "parent_id" => 28,
                "type_id" => 1,
                "level" => 4,
                "is_active" => 1,
            ],
            [
                "id" => 40,
                "name" => "مخزون قطع الغيار",
                "code" => "10103010001",
                "parent_id" => 39,
                "type_id" => 1,
                "level" => 5,
                "is_active" => 1,
            ],
            [
                "id" => 41,
                "name" => "مخزون كفرات",
                "code" => "1010302",
                "parent_id" => 28,
                "type_id" => 1,
                "level" => 4,
                "is_active" => 1,
            ],
            [
                "id" => 42,
                "name" => "مخزون الكفرات",
                "code" => "10103020001",
                "parent_id" => 41,
                "type_id" => 1,
                "level" => 5,
                "is_active" => 1,
            ],
            [
                "id" => 44,
                "name" => "الاصول الثابتة",
                "code" => "10201",
                "parent_id" => 6,
                "type_id" => 1,
                "level" => 3,
                "is_active" => 1,
            ],
            [
                "id" => 45,
                "name" => "العقارات",
                "code" => "1020101",
                "parent_id" => 44,
                "type_id" => 1,
                "level" => 4,
                "is_active" => 1,
            ],
            [
                "id" => 46,
                "name" => "الاراضي",
                "code" => "10201010001",
                "parent_id" => 45,
                "type_id" => 1,
                "level" => 5,
                "is_active" => 1,
            ],
            [
                "id" => 47,
                "name" => "المباني",
                "code" => "10201010002",
                "parent_id" => 45,
                "type_id" => 1,
                "level" => 5,
                "is_active" => 1,
            ],
            [
                "id" => 48,
                "name" => "الالات والمعدات",
                "code" => "1020102",
                "parent_id" => 44,
                "type_id" => 1,
                "level" => 4,
                "is_active" => 1,
            ],
            [
                "id" => 49,
                "name" => "الات ومعدات",
                "code" => "10201020001",
                "parent_id" => 48,
                "type_id" => 1,
                "level" => 5,
                "is_active" => 1,
            ],
            [
                "id" => 50,
                "name" => "سيارات الخدمة",
                "code" => "1020103",
                "parent_id" => 44,
                "type_id" => 1,
                "level" => 4,
                "is_active" => 1,
            ],
            [
                "id" => 51,
                "name" => "سيارات الخدمة",
                "code" => "102010301",
                "parent_id" => 50,
                "type_id" => 1,
                "level" => 5,
                "is_active" => 1,
            ],
            [
                "id" => 52,
                "name" => "الاثاث والمفروشات",
                "code" => "1020104",
                "parent_id" => 44,
                "type_id" => 1,
                "level" => 4,
                "is_active" => 1,
            ],
            [
                "id" => 53,
                "name" => "الاجهزة الكهربائية",
                "code" => "1020105",
                "parent_id" => 44,
                "type_id" => 1,
                "level" => 4,
                "is_active" => 1,
            ],
            [
                "id" => 54,
                "name" => "اثاث ومفروشات",
                "code" => "10201040001",
                "parent_id" => 52,
                "type_id" => 1,
                "level" => 5,
                "is_active" => 1,
            ],
            [
                "id" => 55,
                "name" => "اجهزة كهربائية",
                "code" => "10201050001",
                "parent_id" => 53,
                "type_id" => 1,
                "level" => 5,
                "is_active" => 1,
            ],
            [
                "id" => 56,
                "name" => "مصاريف مدفوعه مقدما",
                "code" => "10301",
                "parent_id" => 7,
                "type_id" => 1,
                "level" => 3,
                "is_active" => 1,
            ],
            [
                "id" => 57,
                "name" => "ايرادات مستحقة",
                "code" => "10302",
                "parent_id" => 7,
                "type_id" => 1,
                "level" => 3,
                "is_active" => 1,
            ],
            [
                "id" => 58,
                "name" => "سلف الموظفين",
                "code" => "10303",
                "parent_id" => 7,
                "type_id" => 1,
                "level" => 3,
                "is_active" => 1,
            ],
            [
                "id" => 59,
                "name" => "عهدة مستديمة",
                "code" => "10304",
                "parent_id" => 7,
                "type_id" => 1,
                "level" => 3,
                "is_active" => 1,
            ],
            [
                "id" => 60,
                "name" => "راس المال",
                "code" => "20401",
                "parent_id" => 11,
                "type_id" => 2,
                "level" => 3,
                "is_active" => 1,
            ],
            [
                "id" => 61,
                "name" => "جاري الشركاء",
                "code" => "20402",
                "parent_id" => 11,
                "type_id" => 2,
                "level" => 3,
                "is_active" => 1,
            ],
            [
                "id" => 62,
                "name" => "الارباح",
                "code" => "20403",
                "parent_id" => 11,
                "type_id" => 2,
                "level" => 3,
                "is_active" => 1,
            ],
            [
                "id" => 63,
                "name" => "الاحتياطيات",
                "code" => "20404",
                "parent_id" => 11,
                "type_id" => 2,
                "level" => 3,
                "is_active" => 1,
            ],
            [
                "id" => 64,
                "name" => "احتياطيات",
                "code" => "2040401",
                "parent_id" => 63,
                "type_id" => 2,
                "level" => 4,
                "is_active" => 1,
            ],
            [
                "id" => 65,
                "name" => "احتياطي قانوني",
                "code" => "2040401001",
                "parent_id" => 64,
                "type_id" => 2,
                "level" => 5,
                "is_active" => 1,
            ],
            [
                "id" => 66,
                "name" => "احتياطي نظامي",
                "code" => "2040401002",
                "parent_id" => 64,
                "type_id" => 2,
                "level" => 5,
                "is_active" => 1,
            ],
            [
                "id" => 67,
                "name" => "الارباح المحتجزة",
                "code" => "2040301",
                "parent_id" => 62,
                "type_id" => 2,
                "level" => 4,
                "is_active" => 1,
            ],
            [
                "id" => 68,
                "name" => "ارباح مرحله",
                "code" => "20403010001",
                "parent_id" => 67,
                "type_id" => 2,
                "level" => 5,
                "is_active" => 1,
            ],
            [
                "id" => 69,
                "name" => "ارباح العام",
                "code" => "2040302",
                "parent_id" => 62,
                "type_id" => 2,
                "level" => 4,
                "is_active" => 1,
            ],
            [
                "id" => 70,
                "name" => "ارباح العام الحالي",
                "code" => "20403020001",
                "parent_id" => 69,
                "type_id" => 2,
                "level" => 5,
                "is_active" => 1,
            ],
            [
                "id" => 71,
                "name" => "جاري الشركاء",
                "code" => "2040201",
                "parent_id" => 61,
                "type_id" => 2,
                "level" => 4,
                "is_active" => 1,
            ],
            [
                "id" => 72,
                "name" => "راس المال",
                "code" => "2040101",
                "parent_id" => 60,
                "type_id" => 2,
                "level" => 4,
                "is_active" => 1,
            ],
            [
                "id" => 73,
                "name" => "راس المال",
                "code" => "20401010001",
                "parent_id" => 72,
                "type_id" => 2,
                "level" => 5,
                "is_active" => 1,
            ],
            [
                "id" => 74,
                "name" => "الموردين",
                "code" => "20101",
                "parent_id" => 8,
                "type_id" => 2,
                "level" => 3,
                "is_active" => 1,
            ],
            [
                "id" => 75,
                "name" => "موردين قطع غيار",
                "code" => "2010101",
                "parent_id" => 74,
                "type_id" => 2,
                "level" => 4,
                "is_active" => 1,
            ],
            [
                "id" => 76,
                "name" => "موردين كفرات",
                "code" => "2010102",
                "parent_id" => 74,
                "type_id" => 2,
                "level" => 4,
                "is_active" => 1,
            ],
            [
                "id" => 77,
                "name" => "موردين ورش صيانة",
                "code" => "2010103",
                "parent_id" => 74,
                "type_id" => 2,
                "level" => 4,
                "is_active" => 1,
            ],
            [
                "id" => 78,
                "name" => "موردين متنوعون",
                "code" => "2010104",
                "parent_id" => 74,
                "type_id" => 2,
                "level" => 4,
                "is_active" => 1,
            ],
            [
                "id" => 79,
                "name" => "مورد قطع غيار نقدي",
                "code" => "20101010001",
                "parent_id" => 75,
                "type_id" => 2,
                "level" => 5,
                "is_active" => 1,
            ],
            [
                "id" => 80,
                "name" => "مورد كفرات نقدي",
                "code" => "20101020001",
                "parent_id" => 76,
                "type_id" => 2,
                "level" => 5,
                "is_active" => 1,
            ],
            [
                "id" => 81,
                "name" => "مورد ورش صيانة نقدي",
                "code" => "20101030001",
                "parent_id" => 77,
                "type_id" => 2,
                "level" => 5,
                "is_active" => 1,
            ],
            [
                "id" => 82,
                "name" => "قروض طويلة الاجل",
                "code" => "20201",
                "parent_id" => 9,
                "type_id" => 2,
                "level" => 3,
                "is_active" => 1,
            ],
            [
                "id" => 83,
                "name" => "مكافأة نهاية الخدمة",
                "code" => "20202",
                "parent_id" => 9,
                "type_id" => 2,
                "level" => 3,
                "is_active" => 1,
            ],
            [
                "id" => 84,
                "name" => "قطع غيار",
                "code" => "30101010002",
                "parent_id" => 14,
                "type_id" => 3,
                "level" => 5,
                "is_active" => 1,
            ],
            [
                "id" => 85,
                "name" => "كفرات",
                "code" => "30101010003",
                "parent_id" => 14,
                "type_id" => 3,
                "level" => 5,
                "is_active" => 1,
            ],
            [
                "id" => 86,
                "name" => "اصلاح وصيانة",
                "code" => "30101010004",
                "parent_id" => 14,
                "type_id" => 3,
                "level" => 5,
                "is_active" => 1,
            ],
            [
                "id" => 87,
                "name" => "تجديد اقامات",
                "code" => "30101020002",
                "parent_id" => 15,
                "type_id" => 3,
                "level" => 5,
                "is_active" => 1,
            ],
            [
                "id" => 88,
                "name" => "كهرباء",
                "code" => "30101020003",
                "parent_id" => 15,
                "type_id" => 3,
                "level" => 5,
                "is_active" => 1,
            ],
            [
                "id" => 89,
                "name" => "مياه",
                "code" => "30101020004",
                "parent_id" => 15,
                "type_id" => 3,
                "level" => 5,
                "is_active" => 1,
            ],
            [
                "id" => 90,
                "name" => "صيانة اخري",
                "code" => "30101020005",
                "parent_id" => 15,
                "type_id" => 3,
                "level" => 5,
                "is_active" => 1,
            ],
            [
                "id" => 91,
                "name" => "ايرادات",
                "code" => "401",
                "parent_id" => 4,
                "type_id" => 4,
                "level" => 2,
                "is_active" => 1,
            ],
            [
                "id" => 92,
                "name" => "ايرادات التشغيل",
                "code" => "40101",
                "parent_id" => 91,
                "type_id" => 4,
                "level" => 3,
                "is_active" => 1,
            ],
            [
                "id" => 93,
                "name" => "ايرادات اخري",
                "code" => "40102",
                "parent_id" => 91,
                "type_id" => 4,
                "level" => 3,
                "is_active" => 1,
            ],
            [
                "id" => 94,
                "name" => "ايرادات تخزين",
                "code" => "4010101",
                "parent_id" => 92,
                "type_id" => 4,
                "level" => 4,
                "is_active" => 1,
            ],
            [
                "id" => 95,
                "name" => "ايرادات التخزين",
                "code" => "40101010001",
                "parent_id" => 94,
                "type_id" => 4,
                "level" => 5,
                "is_active" => 1,
            ],
            [
                "id" => 96,
                "name" => "ايرادات تحميل وتنزيل",
                "code" => "40101010002",
                "parent_id" => 94,
                "type_id" => 4,
                "level" => 5,
                "is_active" => 1,
            ],
            [
                "id" => 97,
                "name" => "الايرادات الاخري",
                "code" => "4010201",
                "parent_id" => 93,
                "type_id" => 4,
                "level" => 4,
                "is_active" => 1,
            ],
            [
                "id" => 98,
                "name" => "ايرادات متنوعة",
                "code" => "40102010001",
                "parent_id" => 97,
                "type_id" => 4,
                "level" => 5,
                "is_active" => 1,
            ],
            [
                "id" => 99,
                "name" => "مصاريف مستحقة",
                "code" => "20301",
                "parent_id" => 10,
                "type_id" => 2,
                "level" => 3,
                "is_active" => 1,
            ],
            [
                "id" => 100,
                "name" => "ايرادات مدفوعه مقدما",
                "code" => "20302",
                "parent_id" => 10,
                "type_id" => 2,
                "level" => 3,
                "is_active" => 1,
            ]
        ];

        foreach ($roots as $root) {
            Account::create($root);
        }
    }
}
